apiVersion: v1
kind: Namespace
metadata:
  name: tracing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service
  namespace: tracing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service
  namespace: tracing
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: tracing
spec:
  ports:
  - name: grpc
    port: 8091
    targetPort: 8091
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: customer-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: tracing
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8090
  selector:
    app: api-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: tracing
    app.kubernetes.io/version: v1
  name: api-service
  namespace: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
      version: v1
  template:
    metadata:
      labels:
        app: api-service
        version: v1
    spec:
      containers:
      - env:
        - name: TEMPO_URL
          value: "http://tempo.observability:4317"
        image: 020644639648.dkr.ecr.eu-west-1.amazonaws.com/cto/tracing-api-service:latest
        name: api-service
        ports:
        - containerPort: 8090
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: api-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/part-of: tracing
    app.kubernetes.io/version: v1
  name: customer-service
  namespace: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
      version: v1
  template:
    metadata:
      labels:
        app: customer-service
        version: v1
    spec:
      containers:
      - env:
        - name: TEMPO_URL
          value: "http://tempo.observability:4317"
        image: 020644639648.dkr.ecr.eu-west-1.amazonaws.com/cto/tracing-customer-service:latest
        name: customer-service
        ports:
        - containerPort: 8091
          name: http
        resources:
          requests:
            cpu: 10m
      serviceAccountName: customer-service