server.port: 8091

spring:
  output:
    ansi:
      enabled: always
  application:
    name: customer-service

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://tempo.observability:4318

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
    io:
      opentelemetry: DEBUG